@startuml

class GUI {
  - account: None
  - plex_access: None
  - size: {"x": 450, "y": 150}
  - pad: {"x": 20, "y": 5}
  - window: None
  - text: str
  - selected_value: None
  + __init__(text: str)
  + create_window(): None
  + create_sessions_list(sessions: list, event_method: classmethod | None): None
  + reset_listbox(listbox_object: object, sessions: list): None
  + run(): None
}

class Plex {
  + check_connect(): None
}

class PlexRPC {
  - instance: PlexServer
  + __init__()
  + sessions(): list
  + data(index: int): dict
  + state(session: object): str
  + is_session_empty(): bool
}

class RPC {
  - rpc: Presence
  - baseurl: str
  - token: str
  - details: None
  - state: None
  - connected: False
  + __init__()
  + do_loop(): None
  + run_rpc(event): None
  + connect(): bool
  + disconnect(): bool
  + define_rpc(session: object): None
  + discord_rpc(): None
}

GUI -- PlexRPC: uses 1..*
RPC -- GUI: uses 1
RPC -- PlexRPC: uses 1
RPC -- Plex: uses 1

@enduml
